bucket: cclug
inboxEmail: "inbox@email.cclug.org.au"
whitelist: 
  - mkuchin@gmail.com
  - mkuchin@tpg.com.au
  - me@tobin.cc
  - dup@tobin.cc
#       "tstarling@wikimedia.org",      // Tim
#  	"neville.bagot@det.nsw.edu.au", // Neville
#  	"robert@thorsby.com.au",        // Robert
#  	"officemail2259@yahoo.com.au",  // Toby
#       "lubos@linux.com"               // Lubos
#       "b.e.smith@computer.org"        // Bruce Smith
#       "juergen.busam@stralion.com"    // Juergen
#       "nathan@nathanseal.com"         // Nathon
